import React, { useEffect, useState } from 'react';
import { API_BASE_URL } from '../config';
import { PageLoader } from '../components/Loader/Loader';
import './TeacherStudentContent.css';
type Row = Record<string, any>;
export default function HallTicketManagement({ schoolId }: { schoolId: number }) {
  const [students, setStudents] = useState<Row[]>([]); const [exams, setExams] = useState<Row[]>([]); const [rows, setRows] = useState<Row[]>([]);
  const [form, setForm] = useState({ studentId:'', examId:'', seatNumber:'', room:'', documentUrl:'', publish:true });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const request = async (path:string, options?:RequestInit) => { const response=await fetch(`${API_BASE_URL}/api/SchoolStudentAdmin${path}`, { ...options, headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${localStorage.getItem('token')}`, ...options?.headers } }); const body=await response.json(); if(!response.ok) throw new Error(body.message||'Request failed.'); return body.data; };
  const load=async()=>{setLoading(true);setError('');try{const [tickets,options]=await Promise.all([request(`/hall-tickets?schoolId=${schoolId}`),request(`/exam-options?schoolId=${schoolId}`)]);setRows(tickets||[]);setExams(options||[]);}catch(failure:any){setError(failure.message);}finally{setLoading(false);}};
  useEffect(()=>{void load();fetch(`${API_BASE_URL}/api/Student/students-by-school?schoolId=${schoolId}&page=1&pageSize=500`,{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}).then(r=>r.json()).then(x=>setStudents(x.data||[])).catch(()=>setStudents([]));},[schoolId]);
  const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await request('/hall-tickets',{method:'POST',body:JSON.stringify({...form,schoolId,studentId:Number(form.studentId),examId:Number(form.examId)})});await load();}catch(failure:any){setError(failure.message);}finally{setSaving(false);}};
  return <div className="tw tsc"><section className="tw-hero"><div><span className="tw-eyebrow">STUDENT SERVICES</span><h2>Hall tickets</h2><p>Assign exam seats and publish tickets for students.</p></div></section>{error&&<div className="tw-error" role="alert">{error}</div>}{loading&&<PageLoader label="Loading hall tickets..."/>}<form className="tw-panel tsc-form" onSubmit={save}><label>Student<select required value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})}><option value="">Choose student</option>{students.map(x=><option key={x.id||x.studentId} value={x.id||x.studentId}>{x.studentName||x.name}</option>)}</select></label><label>Exam<select required value={form.examId} onChange={e=>setForm({...form,examId:e.target.value})}><option value="">Choose exam</option>{exams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Seat number<input required maxLength={50} value={form.seatNumber} onChange={e=>setForm({...form,seatNumber:e.target.value})}/></label><label>Room<input required maxLength={100} value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/></label><label className="tsc-full">Ticket link<input type="url" value={form.documentUrl} onChange={e=>setForm({...form,documentUrl:e.target.value})}/></label><label className="tsc-check"><input type="checkbox" checked={form.publish} onChange={e=>setForm({...form,publish:e.target.checked})}/>Publish now</label><button className="btn btn-primary" disabled={saving}>{saving?'Saving...':'Save ticket'}</button></form><section className="tsc-list">{rows.map(x=><article className="tw-panel tsc-record" key={x.id}><h4>{x.studentName} - {x.examName}</h4><p>Seat {x.seatNumber} - Room {x.room} - {x.isPublished?'Published':'Draft'}</p></article>)}{!loading&&!rows.length&&<p className="tw-empty">No hall tickets yet.</p>}</section></div>;
}
