import React,{useEffect,useMemo,useState}from'react';
import{PERMISSION_API_BASE_URL}from'../config';import'./PermissionManagement.css';import'./PermissionManagement.mobile.css';
type Role={id:number;roleName:string;description?:string;isActive:boolean};type Cell={actionId:number;actionName:string;permissionId?:number};type Page={id:number;name:string;permissions:Cell[]};type Module={id:number;name:string;pages:Page[]};
const auth=()=>({Authorization:`Bearer ${localStorage.getItem('token')}`,'Content-Type':'application/json'});
async function api(path:string,options:RequestInit={}){const r=await fetch(`${PERMISSION_API_BASE_URL}/api/permissions/${path}`,{...options,headers:{...auth(),...(options.headers||{})},cache:'no-store'});const text=await r.text();let data:any=null;if(text)try{data=JSON.parse(text)}catch{throw Error(`Permission API returned HTML/text instead of JSON (${r.status}). Restart the updated API at ${PERMISSION_API_BASE_URL}.`)}if(r.status===401)throw Error('Session expired. Please log in again.');if(r.status===403)throw Error(data?.message||'Only Super Admin can manage permissions.');if(!r.ok)throw Error(data?.message||`Permission API failed (${r.status}).`);return data}
export default function PermissionManagement(){
 const[tab,setTab]=useState('matrix'),[roles,setRoles]=useState<Role[]>([]),[catalog,setCatalog]=useState<Module[]>([]),[selected,setSelected]=useState<number>(),[grants,setGrants]=useState<Set<number>>(new Set()),[search,setSearch]=useState(''),[expanded,setExpanded]=useState<Set<number>>(new Set()),[stats,setStats]=useState<any>(),[features,setFeatures]=useState<any[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[newRole,setNewRole]=useState({name:'',description:''});
 const load=async()=>{setLoading(true);try{const[r,c,d,f]=await Promise.all(['roles','catalog','dashboard','features'].map(api));setRoles(r);setCatalog(c);setStats(d);setFeatures(f);setExpanded(new Set(c.map((x:Module)=>x.id)));setSelected(v=>v||r[0]?.id);setMessage('')}catch(e:any){setMessage(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(selected)api(`roles/${selected}`).then(x=>setGrants(new Set(x))).catch(e=>setMessage(e.message))},[selected]);
 const actions=useMemo(()=>catalog.flatMap(m=>m.pages).find(p=>p.permissions.length)?.permissions||[],[catalog]);const shown=useMemo(()=>catalog.map(m=>({...m,pages:m.pages.filter(p=>(m.name+' '+p.name).toLowerCase().includes(search.toLowerCase()))})).filter(m=>m.pages.length),[catalog,search]);
 const toggle=(id?:number)=>id&&setGrants(g=>{const n=new Set(g);n.has(id)?n.delete(id):n.add(id);return n});const moduleToggle=(m:Module,on:boolean)=>setGrants(g=>{const n=new Set(g);m.pages.flatMap(p=>p.permissions).forEach(c=>c.permissionId&&(on?n.add(c.permissionId):n.delete(c.permissionId)));return n});const allIds=catalog.flatMap(m=>m.pages.flatMap(p=>p.permissions.flatMap(c=>c.permissionId?[c.permissionId]:[])));
 const save=async()=>{if(!selected)return;try{await api(`roles/${selected}`,{method:'PUT',body:JSON.stringify({permissionIds:[...grants]})});setMessage('Permissions saved. Changes take effect immediately.');await load()}catch(e:any){setMessage(e.message)}};const create=async()=>{if(!newRole.name.trim()){setMessage('Role name is required.');return}try{await api('roles',{method:'POST',body:JSON.stringify({...newRole,isActive:true,schoolId:Number(localStorage.getItem('schoolId'))||null})});setNewRole({name:'',description:''});await load();setMessage('Role created.')}catch(e:any){setMessage(e.message)}};
 return <div className="permission-page"><div className="permission-heading"><div><h2>Role & Permission Management</h2><p>Control menus, pages and actions without code changes.</p></div>{tab==='matrix'&&<button className="btn btn-primary" disabled={!selected||loading} onClick={save}>Save Changes</button>}</div>{message&&<div className="permission-message">{message}</div>}<div className="permission-stats">{[['Total Roles',stats?.totalRoles],['Total Employees',stats?.totalEmployees],['Active Permissions',stats?.activePermissions],['Recent Changes',stats?.recentlyModified?.length]].map(([a,b])=><div className="permission-stat" key={String(a)}><span>{a}</span><strong>{b??0}</strong></div>)}</div>
 <div className="permission-tabs">{[['matrix','Permission Matrix'],['roles','Roles'],['employees','Employee Access'],['features','Feature Toggles'],['audit','Audit Log']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{loading&&<div className="permission-empty">Loading permission catalog…</div>}
 {!loading&&tab==='matrix'&&<><div className="permission-toolbar"><select value={selected||''} onChange={e=>setSelected(+e.target.value)}><option value="" disabled>Select role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.roleName}</option>)}</select><input placeholder="Search modules or pages" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setGrants(new Set(allIds))}>Select All</button><button onClick={()=>setGrants(new Set())}>Clear All</button></div>{!catalog.length?<div className="permission-empty">No permission catalog was returned.</div>:<div className="permission-table-wrap"><table className="permission-table"><thead><tr><th>Module / Page</th>{actions.map(a=><th key={a.actionId}>{a.actionName}</th>)}</tr></thead><tbody>{shown.map(m=><React.Fragment key={m.id}><tr className="module-row"><td><button onClick={()=>setExpanded(s=>{const n=new Set(s);n.has(m.id)?n.delete(m.id):n.add(m.id);return n})}>{expanded.has(m.id)?'▾':'▸'} {m.name}</button></td><td colSpan={actions.length}><button onClick={()=>moduleToggle(m,true)}>Grant module</button> <button onClick={()=>moduleToggle(m,false)}>Clear</button></td></tr>{expanded.has(m.id)&&m.pages.map(p=><tr key={p.id}><td className="page-name">{p.name}</td>{p.permissions.map(c=><td key={c.actionId}><input aria-label={`${p.name} ${c.actionName}`} type="checkbox" checked={!!c.permissionId&&grants.has(c.permissionId)} onChange={()=>toggle(c.permissionId)}/></td>)}</tr>)}</React.Fragment>)}</tbody></table></div>}</>}
 {!loading&&tab==='roles'&&<div className="permission-grid"><div className="permission-card"><h3>Create Role</h3><input placeholder="Role name" value={newRole.name} onChange={e=>setNewRole({...newRole,name:e.target.value})}/><textarea placeholder="Description" value={newRole.description} onChange={e=>setNewRole({...newRole,description:e.target.value})}/><button className="btn btn-primary" onClick={create}>Create Role</button></div><div className="permission-card"><h3>Existing Roles</h3>{roles.map(r=><div key={r.id} className="role-line"><div><strong>{r.roleName}</strong><small>{r.description||'No description'}</small></div><span className={r.isActive?'status-active':'status-inactive'}>{r.isActive?'Active':'Inactive'}</span></div>)}</div></div>}
 {!loading&&tab==='employees'&&<div className="permission-empty"><h3>Employee Access</h3><p>Select employees and assign one or multiple roles with individual overrides.</p></div>}
 {!loading&&tab==='features'&&<div className="permission-card"><h3>Feature Toggles</h3>{features.map(f=><label key={f.id} className="feature-line"><span><strong>{f.name}</strong><small>{f.key}</small></span><input type="checkbox" checked={f.isEnabled} onChange={async e=>{try{await api(`features/${f.id}`,{method:'PUT',body:JSON.stringify({enabled:e.target.checked})});await load()}catch(x:any){setMessage(x.message)}}}/></label>)}</div>}
 {!loading&&tab==='audit'&&<div className="permission-card"><h3>Recently Modified Permissions</h3>{!stats?.recentlyModified?.length?<p>No permission changes recorded yet.</p>:stats.recentlyModified.map((x:any)=><div key={x.id} className="audit-line"><span><strong>{x.action}</strong> · {x.entityType} #{x.entityId}</span><time>{new Date(x.createdAt).toLocaleString()}</time></div>)}</div>}</div>}
