import React, { useEffect, useMemo, useState } from 'react';
import { API_BASE_URL } from '../config';
import './StudentPromotion.css';

type Action = 'Promote' | 'Repeat' | 'Transfer' | 'Left';
interface Lookup { id: number; name?: string; classId?: number; yearStart?: string; yearEnd?: string; }
interface StudentRow { enrollmentId:number; studentId:number; admissionNo:string; studentName:string; className:string; sectionName:string; result:string; suggestedAction:Action; selected:boolean; action:Action; toClassId:string; toSectionId:string; rollNumber:string; }
interface Props { selectedSchoolId:number|null; initialView?:'promotion'|'history'; }

const StudentPromotion:React.FC<Props>=({selectedSchoolId,initialView='promotion'})=>{
 const [view,setView]=useState<'promotion'|'history'>(initialView);
 const [sessions,setSessions]=useState<Lookup[]>([]),[classes,setClasses]=useState<Lookup[]>([]),[sections,setSections]=useState<Lookup[]>([]);
 const [currentSession,setCurrentSession]=useState(''),[nextSession,setNextSession]=useState(''),[currentClass,setCurrentClass]=useState(''),[currentSection,setCurrentSection]=useState('');
 const [defaultClass,setDefaultClass]=useState(''),[defaultSection,setDefaultSection]=useState('');
 const [rows,setRows]=useState<StudentRow[]>([]),[history,setHistory]=useState<any[]>([]);
 const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[preview,setPreview]=useState(false),[message,setMessage]=useState('');
 const [options,setOptions]=useState({assignFees:true,copyTransport:false,copyBusRoute:false,assignBookKit:false,assignUniformKit:false,generateRollNumbers:true,carryOptionalSettings:true});
 const headers=()=>({accept:'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`,'Content-Type':'application/json'});
 const fmtSession=(s:Lookup)=>`${new Date(s.yearStart!).getFullYear()}-${new Date(s.yearEnd!).getFullYear()}`;
 useEffect(()=>{setView(initialView)},[initialView]);
 useEffect(()=>{if(!selectedSchoolId)return;setRows([]);Promise.all([
  fetch(`${API_BASE_URL}/api/Student/enrollment-info?schoolId=${selectedSchoolId}`,{headers:headers()}).then(r=>r.json())
 ]).then(([r])=>{setSessions(r.data?.sessions||[]);setClasses(r.data?.classes||[]);setSections(r.data?.sections||[])}).catch(()=>setMessage('Unable to load academic options.'))},[selectedSchoolId]); // eslint-disable-line
 useEffect(()=>{if(view==='history'&&selectedSchoolId)loadHistory()},[view,selectedSchoolId]); // eslint-disable-line
 const currentSections=sections.filter(x=>x.classId===Number(currentClass));
 const destinationSections=sections.filter(x=>x.classId===Number(defaultClass));
 const selected=rows.filter(x=>x.selected);
 const summary=useMemo(()=>({loaded:rows.length,promote:selected.filter(x=>x.action==='Promote').length,repeat:selected.filter(x=>x.action==='Repeat').length,transfer:selected.filter(x=>x.action==='Transfer').length,left:selected.filter(x=>x.action==='Left').length}),[rows,selected]);
 const loadStudents=async()=>{if(!currentSession||!nextSession||!currentClass||!currentSection){setMessage('Select current/next sessions, class, and section.');return}setLoading(true);setMessage('');try{const q=new URLSearchParams({schoolId:String(selectedSchoolId),currentSessionId:currentSession,classId:currentClass,sectionId:currentSection});const r=await fetch(`${API_BASE_URL}/api/student-promotion/students?${q}`,{headers:headers()});const j=await r.json();if(!r.ok)throw new Error(j.message);setRows((j.data||[]).map((x:any)=>({...x,selected:true,action:x.suggestedAction||'Promote',toClassId:defaultClass,toSectionId:defaultSection,rollNumber:''})));if(!(j.data||[]).length)setMessage('No active students found for this class and session.')}catch(e:any){setMessage(e.message||'Unable to load students.')}finally{setLoading(false)}};
 const update=(id:number,patch:Partial<StudentRow>)=>setRows(v=>v.map(x=>x.enrollmentId===id?{...x,...patch}:x));
 const applyDestination=()=>setRows(v=>v.map(x=>x.selected&&['Promote','Repeat'].includes(x.action)?{...x,toClassId:defaultClass,toSectionId:defaultSection}:x));
 const validate=()=>{if(!selected.length){setMessage('Select at least one student.');return false}const invalid=selected.find(x=>['Promote','Repeat'].includes(x.action)&&(!x.toClassId||!x.toSectionId));if(invalid){setMessage(`Choose a destination for ${invalid.studentName}.`);return false}return true};
 const execute=async()=>{if(!validate())return;setSaving(true);setMessage('');try{const body={schoolId:selectedSchoolId,currentSessionId:Number(currentSession),nextSessionId:Number(nextSession),...options,students:selected.map(x=>({enrollmentId:x.enrollmentId,action:x.action,toClassId:x.toClassId?Number(x.toClassId):null,toSectionId:x.toSectionId?Number(x.toSectionId):null,rollNumber:x.rollNumber||null}))};const r=await fetch(`${API_BASE_URL}/api/student-promotion/promote`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message);const warnings=j.data?.warnings?.length?` Warnings: ${j.data.warnings.join(' ')}`:'';setMessage(`${j.message}${warnings}`);setRows([]);setPreview(false)}catch(e:any){setMessage(e.message||'Promotion failed.')}finally{setSaving(false)}};
 const loadHistory=async()=>{try{const r=await fetch(`${API_BASE_URL}/api/student-promotion/history?schoolId=${selectedSchoolId}`,{headers:headers()});const j=await r.json();setHistory(j.data||[])}catch{setMessage('Unable to load promotion history.')}};
 if(!selectedSchoolId)return <div className="promotion-card">Please select a school.</div>;
 return <div className="promotion-page">
  <div className="management-tabs"><button className={`management-tab ${view==='promotion'?'active':''}`} onClick={()=>setView('promotion')}>Student Promotion</button><button className={`management-tab ${view==='history'?'active':''}`} onClick={()=>setView('history')}>Promotion History</button></div>
  {message&&<div className="promotion-message">{message}</div>}
  {view==='history'?<div className="promotion-card"><h2>Promotion History</h2><div className="promotion-table-wrap"><table className="promotion-table"><thead><tr><th>Student</th><th>From Session</th><th>To Session</th><th>From Class</th><th>To Class</th><th>Type</th><th>Date</th><th>Remarks</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.studentName}</td><td>{x.fromSession}</td><td>{x.toSession}</td><td>{x.fromClass}</td><td>{x.toClass}</td><td><span className={`action-badge ${String(x.type).toLowerCase()}`}>{x.type}</span></td><td>{new Date(x.promotionDate).toLocaleDateString()}</td><td>{x.remarks||'-'}</td></tr>)}{!history.length&&<tr><td colSpan={8}>No promotion history available.</td></tr>}</tbody></table></div></div>:
  <><div className="promotion-card"><h2>1. Select source and destination sessions</h2><div className="promotion-grid"><label>Current Session *<select value={currentSession} onChange={e=>{setCurrentSession(e.target.value);setRows([])}}><option value="">Select</option>{sessions.map(s=><option key={s.id} value={s.id}>{fmtSession(s)}</option>)}</select></label><label>Next Session *<select value={nextSession} onChange={e=>setNextSession(e.target.value)}><option value="">Select</option>{sessions.filter(s=>String(s.id)!==currentSession).map(s=><option key={s.id} value={s.id}>{fmtSession(s)}</option>)}</select></label><label>Current Class *<select value={currentClass} onChange={e=>{setCurrentClass(e.target.value);setCurrentSection('');setRows([])}}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Current Section *<select value={currentSection} onChange={e=>setCurrentSection(e.target.value)}><option value="">Select</option>{currentSections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><button className="btn btn-primary" onClick={loadStudents} disabled={loading}>{loading?'Loading...':'Load Students'}</button></div>
  {rows.length>0&&<><div className="promotion-card"><h2>2. Set common destination</h2><div className="promotion-grid"><label>Move To Class<select value={defaultClass} onChange={e=>{setDefaultClass(e.target.value);setDefaultSection('')}}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Move To Section<select value={defaultSection} onChange={e=>setDefaultSection(e.target.value)}><option value="">Select</option>{destinationSections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><button className="btn" onClick={applyDestination}>Apply to selected students</button></div>
  <div className="promotion-card"><h2>3. Review students and actions</h2><div className="promotion-table-wrap"><table className="promotion-table"><thead><tr><th><input type="checkbox" checked={selected.length===rows.length} onChange={e=>setRows(v=>v.map(x=>({...x,selected:e.target.checked})))}/></th><th>Admission No</th><th>Student</th><th>Current Class</th><th>Result</th><th>Action</th><th>New Class</th><th>New Section</th><th>Roll No</th></tr></thead><tbody>{rows.map(x=>{const needsDestination=['Promote','Repeat'].includes(x.action);return <tr key={x.enrollmentId}><td><input type="checkbox" checked={x.selected} onChange={e=>update(x.enrollmentId,{selected:e.target.checked})}/></td><td>{x.admissionNo}</td><td>{x.studentName}</td><td>{x.className} / {x.sectionName}</td><td>{x.result}</td><td><select value={x.action} onChange={e=>update(x.enrollmentId,{action:e.target.value as Action})}>{(['Promote','Repeat','Transfer','Left'] as Action[]).map(a=><option key={a}>{a}</option>)}</select></td><td><select disabled={!needsDestination} value={x.toClassId} onChange={e=>update(x.enrollmentId,{toClassId:e.target.value,toSectionId:''})}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td><select disabled={!needsDestination} value={x.toSectionId} onChange={e=>update(x.enrollmentId,{toSectionId:e.target.value})}><option value="">Select</option>{sections.filter(s=>s.classId===Number(x.toClassId)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></td><td><input disabled={!needsDestination||options.generateRollNumbers} value={x.rollNumber} onChange={e=>update(x.enrollmentId,{rollNumber:e.target.value})} placeholder={options.generateRollNumbers?'Auto':'Roll no'}/></td></tr>})}</tbody></table></div></div>
  <div className="promotion-card"><h2>4. Carry-forward options</h2><div className="promotion-options">{Object.entries({assignFees:'Assign/copy fee assignments',copyTransport:'Copy transport assignment',copyBusRoute:'Copy bus route',assignBookKit:'Assign destination book kit',assignUniformKit:'Assign destination uniform kit',generateRollNumbers:'Generate roll numbers automatically',carryOptionalSettings:'Carry shared profile settings'}).map(([key,label])=><label key={key}><input type="checkbox" checked={(options as any)[key]} onChange={e=>setOptions(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}</div><button className="btn btn-primary" onClick={()=>{if(validate())setPreview(true)}}>Preview Promotion</button></div></>}
  {preview&&<div className="promotion-modal"><div className="promotion-preview"><h2>Promotion Preview</h2><p><b>Current:</b> {sessions.find(x=>String(x.id)===currentSession)?fmtSession(sessions.find(x=>String(x.id)===currentSession)!):'-'}</p><p><b>Next:</b> {sessions.find(x=>String(x.id)===nextSession)?fmtSession(sessions.find(x=>String(x.id)===nextSession)!):'-'}</p><div className="preview-counts"><span>Selected: {selected.length}</span><span>Promote: {summary.promote}</span><span>Repeat: {summary.repeat}</span><span>Transfer: {summary.transfer}</span><span>Left: {summary.left}</span></div><p>This operation preserves old enrollments and creates new records only for Promote/Repeat.</p><div className="preview-actions"><button className="btn" onClick={()=>setPreview(false)}>Back</button><button className="btn btn-primary" disabled={saving} onClick={execute}>{saving?'Processing...':'Confirm & Promote'}</button></div></div></div>}
  </>}
 </div>
};
export default StudentPromotion;
