import React, { useEffect, useState } from 'react';
import { API_BASE_URL } from '../config';
import { PageLoader } from '../components/Loader/Loader';
import './TeacherStudentContent.css';
type Row = Record<string, any>;
type Tab = 'Clubs' | 'Houses' | 'Transport Alerts' | 'Lost & Found' | 'Library Reservations' | 'Registrations';
export default function StudentCommunityManagement({ schoolId }: { schoolId: number }) {
  const [tab, setTab] = useState<Tab>('Clubs');
  const [data, setData] = useState<Row | null>(null);
  const [students, setStudents] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ name:'', description:'', schedule:'', coordinator:'', studentId:'', houseId:'', points:'0', title:'', message:'', effectiveDate:'', targetedStudentId:'' });
  const request = async (path:string, init?:RequestInit) => { const response=await fetch(`${API_BASE_URL}/api/SchoolCommunityAdmin${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('token')}`,...init?.headers}}); const body=await response.json(); if(!response.ok) throw new Error(body.message||'Could not save.'); return body.data; };
  const load = async () => {setLoading(true);setError('');try{setData(await request(`/overview?schoolId=${schoolId}`));}catch(failure:any){setError(failure.message);}finally{setLoading(false);}};
  useEffect(()=>{void load();fetch(`${API_BASE_URL}/api/Student/students-by-school?schoolId=${schoolId}&page=1&pageSize=500`,{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}).then(r=>r.json()).then(x=>setStudents(x.data||[])).catch(()=>setStudents([]));},[schoolId]);
  const save=async(path:string,payload:object)=>{setSaving(true);setError('');try{await request(path,{method:'POST',body:JSON.stringify({schoolId,...payload})});await load();}catch(failure:any){setError(failure.message);}finally{setSaving(false);}};
  const studentSelect=(value:string,onChange:(value:string)=>void,optional=false)=><select required={!optional} value={value} onChange={e=>onChange(e.target.value)}><option value="">{optional?'All students':'Choose student'}</option>{students.map(x=><option key={x.id||x.studentId} value={x.id||x.studentId}>{x.studentName||x.name}</option>)}</select>;
  return <div className="tw tsc"><section className="tw-hero"><div><span className="tw-eyebrow">STUDENT SERVICES</span><h2>Student Community</h2><p>Publish activities and transport updates, assign houses, and review student posts.</p></div></section>
    <div className="tw-tabs tsc-tabs">{(['Clubs','Houses','Transport Alerts','Lost & Found','Library Reservations','Registrations'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
    {error&&<div className="tw-error" role="alert">{error}</div>}{loading&&<PageLoader label="Loading student community..."/>}
    {tab==='Clubs'&&<><form className="tw-panel tsc-form" onSubmit={e=>{e.preventDefault();void save('/clubs',{name:form.name,description:form.description,schedule:form.schedule,coordinator:form.coordinator});}}><h3>Create club</h3><label>Name<input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Schedule<input maxLength={200} value={form.schedule} onChange={e=>setForm({...form,schedule:e.target.value})}/></label><label>Coordinator<input maxLength={120} value={form.coordinator} onChange={e=>setForm({...form,coordinator:e.target.value})}/></label><label className="tsc-full">Description<textarea maxLength={1000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary" disabled={saving}>Create club</button></form><section className="tsc-list">{data?.clubs?.map((x:Row)=><article className="tw-panel tsc-record" key={x.id}><h4>{x.name}</h4><p>{x.description}</p><small>{x.schedule} - {x.coordinator}</small></article>)}{data?.clubMemberships?.map((x:Row)=><div className="tw-panel" key={'m'+x.id}>{x.studentName} joined {x.clubName}</div>)}</section></>}
    {tab==='Houses'&&<><form className="tw-panel tsc-form" onSubmit={e=>{e.preventDefault();void save('/houses',{name:form.name});}}><h3>Create house</h3><label>Name<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><button className="btn btn-primary" disabled={saving}>Create house</button></form><form className="tw-panel tsc-form" onSubmit={e=>{e.preventDefault();void save('/houses/assign',{studentId:Number(form.studentId),houseId:Number(form.houseId)});}}><h3>Assign student</h3><label>Student{studentSelect(form.studentId,value=>setForm({...form,studentId:value}))}</label><label>House<select required value={form.houseId} onChange={e=>setForm({...form,houseId:e.target.value})}><option value="">Choose house</option>{data?.houses?.map((x:Row)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="btn btn-primary" disabled={saving}>Assign</button></form><section className="tsc-list">{data?.houses?.map((x:Row)=><article className="tw-panel tsc-record" key={x.id}><h4>{x.name} - {x.points} points</h4><form className="tsc-form" onSubmit={e=>{e.preventDefault();void save(`/houses/${x.id}/points`,{points:Number(form.points)});}}><label>Set points<input type="number" min="0" value={form.points} onChange={e=>setForm({...form,points:e.target.value})}/></label><button className="btn" disabled={saving}>Save points</button></form>{data?.houseMemberships?.filter((m:Row)=>m.houseId===x.id).map((m:Row)=><p key={m.studentId}>{m.studentName}</p>)}</article>)}</section></>}
    {tab==='Transport Alerts'&&<><form className="tw-panel tsc-form" onSubmit={e=>{e.preventDefault();void save('/transport-alerts',{studentId:form.targetedStudentId?Number(form.targetedStudentId):null,title:form.title,message:form.message,effectiveDate:form.effectiveDate});}}><h3>Publish transport update</h3><label>Audience{studentSelect(form.targetedStudentId,value=>setForm({...form,targetedStudentId:value}),true)}</label><label>Effective date<input required type="date" value={form.effectiveDate} onChange={e=>setForm({...form,effectiveDate:e.target.value})}/></label><label>Title<input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="tsc-full">Message<textarea required maxLength={1000} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button className="btn btn-primary" disabled={saving}>Publish update</button></form><section className="tsc-list">{data?.transportAlerts?.map((x:Row)=><article className="tw-panel tsc-record" key={x.id}><h4>{x.title}</h4><p>{x.message}</p><small>{String(x.effectiveDate).slice(0,10)} - {x.studentId?'One student':'All students'}</small></article>)}</section></>}
    {tab==='Lost & Found'&&<section className="tsc-list">{data?.lostFound?.length?data.lostFound.map((x:Row)=><article className="tw-panel tsc-record" key={x.id}><span className="tw-pill">{x.isApproved?'Published':'Pending'}</span><h4>{x.kind}: {x.title}</h4><p>{x.description}</p><small>Submitted by {x.studentName}</small>{!x.isApproved&&<button className="btn btn-primary" disabled={saving} onClick={()=>void save(`/lost-found/${x.id}/review`,{approve:true})}>Approve post</button>}</article>):<p className="tw-empty">No posts yet.</p>}</section>}
    {tab==='Library Reservations'&&<section className="tsc-list">{data?.reservations?.length?data.reservations.map((x:Row)=><article className="tw-panel tsc-record" key={x.id}><h4>{x.bookName}</h4><p>{x.studentName} - {x.status}</p><div className="tsc-review">{['Ready','Collected','Cancelled'].map(status=><button className="btn" disabled={saving} key={status} onClick={()=>void save(`/library-reservations/${x.id}/status`,{status})}>{status}</button>)}</div></article>):<p className="tw-empty">No reservations yet.</p>}</section>}
    {tab==='Registrations'&&<section className="tsc-list">{data?.eventRegistrations?.map((x:Row)=><article className="tw-panel tsc-record" key={x.id}><h4>{x.studentName}</h4><p>Registered for {x.eventName}</p></article>)}{!data?.eventRegistrations?.length&&<p className="tw-empty">No event registrations.</p>}</section>}
  </div>;
}
