import React, { useEffect, useState } from 'react';
import { PageLoader } from '../components/Loader/Loader';
import { teacherRequest } from './TeacherWorkspace';
import './TeacherStudentContent.css';
type Row = Record<string, any>;
export default function TeacherDiscussions() {
  const [options, setOptions] = useState<Row[]>([]); const [threads, setThreads] = useState<Row[]>([]); const [posts, setPosts] = useState<Row[]>([]);
  const [selected, setSelected] = useState<Row | null>(null); const [sectionId, setSectionId] = useState(''); const [title, setTitle] = useState(''); const [reply, setReply] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async()=>{setLoading(true);setError('');try{const [o,t]=await Promise.all([teacherRequest('/api/Teacher/teaching-options'),teacherRequest('/api/Teacher/discussions')]);setOptions(o.data||[]);setThreads(t.data||[]);}catch(failure:any){setError(failure.message);}finally{setLoading(false);}};
  const loadPosts=async(id:number)=>{try{const r=await teacherRequest(`/api/Teacher/discussions/${id}/posts`);setPosts(r.data||[]);}catch(failure:any){setError(failure.message);}};
  useEffect(()=>{void load();},[]);
  const save=async(path:string,body?:object)=>{setSaving(true);setError('');try{await teacherRequest(path,{method:'POST',body:JSON.stringify(body||{})});await load();if(selected)await loadPosts(selected.id);return true;}catch(failure:any){setError(failure.message);return false;}finally{setSaving(false);}};
  const sections=Array.from(new Map(options.map(x=>[x.sectionId,x])).values());
  return <div className="tw tsc"><section className="tw-hero"><div><span className="tw-eyebrow">CLASSROOM</span><h2>Discussions</h2><p>Open class topics and approve student replies before classmates see them.</p></div></section>{error&&<div className="tw-error" role="alert">{error}</div>}{loading&&<PageLoader label="Loading discussions…"/>}<form className="tw-panel tsc-form" onSubmit={async e=>{e.preventDefault();if(await save('/api/Teacher/discussions',{sectionId:Number(sectionId),title}))setTitle('');}}><label>Class<select required value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">Choose class</option>{sections.map(x=><option value={x.sectionId} key={x.sectionId}>{x.className} · {x.sectionName}</option>)}</select></label><label>Discussion topic<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="btn btn-primary" disabled={saving}>Open discussion</button></form><section className="tw-panel"><h3>Class topics</h3>{threads.map(x=><button className="btn" style={{margin:'5px'}} key={x.id} onClick={()=>{setSelected(x);void loadPosts(x.id);}}>{x.title}</button>)}{!threads.length&&<p className="tw-empty">No discussions opened yet.</p>}</section>{selected&&<section className="tw-panel"><h3>{selected.title}</h3>{posts.map(x=><article className="tsc-record" key={x.id}><span className="tw-pill">{x.staffId?'Teacher':x.isApproved?'Approved':'Awaiting review'}</span><p>{x.body}</p>{!x.isApproved&&<button className="btn btn-primary" disabled={saving} onClick={()=>void save(`/api/Teacher/discussions/posts/${x.id}/approve`)}>Approve reply</button>}</article>)}<form className="tsc-form" onSubmit={async e=>{e.preventDefault();if(await save(`/api/Teacher/discussions/${selected.id}/posts`,{body:reply}))setReply('');}}><label className="tsc-full">Teacher reply<textarea required maxLength={2000} value={reply} onChange={e=>setReply(e.target.value)}/></label><button className="btn btn-primary" disabled={saving}>Reply</button></form></section>}</div>;
}
